/* 회원 */
DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

/* 찜목록 */
DROP TABLE JJIM 
	CASCADE CONSTRAINTS;

/* 리뷰게시판 */
DROP TABLE REBOARD 
	CASCADE CONSTRAINTS;

/* 미국영화게시판 */
DROP TABLE ARMOVIE 
	CASCADE CONSTRAINTS;

/* 일본영화게시판 */
DROP TABLE JNMOVIE 
	CASCADE CONSTRAINTS;

/* 회원등급 */
DROP TABLE ROLE 
	CASCADE CONSTRAINTS;

/* 중국영화게시판 */
DROP TABLE CNMOVIE 
	CASCADE CONSTRAINTS;

/* 한국영화게시판 */
DROP TABLE KRMOVIE 
	CASCADE CONSTRAINTS;

/* 유럽영화게시판 */
DROP TABLE EUMOVIE 
	CASCADE CONSTRAINTS;

/* 공지사항 */
DROP TABLE TABLE 
	CASCADE CONSTRAINTS;

/* 덧글 */
DROP TABLE RECOMENT 
	CASCADE CONSTRAINTS;

/* 회원 */
CREATE TABLE MEMBER (
	ID VARCHAR2(100) NOT NULL, /* 아이디 */
	PWD VARCHAR2(1000) NOT NULL, /* 비밀번호 */
	IDTIME TIMESTAMP NOT NULL, /* 가입시간 */
	PROFILE VARCHAR2(100), /* 프로필 */
	NICK VARCHAR2(30) NOT NULL /* 닉네임 */
);

COMMENT ON TABLE MEMBER IS '회원';

COMMENT ON COLUMN MEMBER.ID IS '아이디';

COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';

COMMENT ON COLUMN MEMBER.IDTIME IS '가입시간';

COMMENT ON COLUMN MEMBER.PROFILE IS '프로필';

COMMENT ON COLUMN MEMBER.NICK IS '닉네임';

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		ID ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			ID
		);

/* 찜목록 */
CREATE TABLE JJIM (
	JSEQ NUMBER NOT NULL, /* 찜번호 */
	ID VARCHAR2(100) NOT NULL, /* 아이디 */
	RESEQ NUMBER NOT NULL, /* 리뷰글번호 */
	ARSEQ NUMBER NOT NULL, /* 미국영화번호 */
	CNSEQ NUMBER NOT NULL, /* 중국영화번호 */
	JNSEQ NUMBER NOT NULL, /* 일본영화번호 */
	EUSEQ NUMBER NOT NULL, /* 유럽영화번호 */
	KRSEQ NUMBER NOT NULL /* 한국영화번호 */
);

COMMENT ON TABLE JJIM IS '찜목록';

COMMENT ON COLUMN JJIM.JSEQ IS '찜번호';

COMMENT ON COLUMN JJIM.ID IS '아이디';

COMMENT ON COLUMN JJIM.RESEQ IS '리뷰글번호';

COMMENT ON COLUMN JJIM.ARSEQ IS '미국영화번호';

COMMENT ON COLUMN JJIM.CNSEQ IS '중국영화번호';

COMMENT ON COLUMN JJIM.JNSEQ IS '일본영화번호';

COMMENT ON COLUMN JJIM.EUSEQ IS '유럽영화번호';

COMMENT ON COLUMN JJIM.KRSEQ IS '한국영화번호';

CREATE UNIQUE INDEX PK_JJIM
	ON JJIM (
		JSEQ ASC
	);

ALTER TABLE JJIM
	ADD
		CONSTRAINT PK_JJIM
		PRIMARY KEY (
			JSEQ
		);

/* 리뷰게시판 */
CREATE TABLE REBOARD (
	RESEQ NUMBER NOT NULL, /* 리뷰글번호 */
	RENAME VARCHAR2(100) NOT NULL, /* 리뷰글이름 */
	RECONTENT VARCHAR2(1000) NOT NULL, /* 리뷰내용 */
	REPHOTO VARCHAR2(100) /* 리뷰사진 */
);

COMMENT ON TABLE REBOARD IS '리뷰게시판';

COMMENT ON COLUMN REBOARD.RESEQ IS '리뷰글번호';

COMMENT ON COLUMN REBOARD.RENAME IS '리뷰글이름';

COMMENT ON COLUMN REBOARD.RECONTENT IS '리뷰내용';

COMMENT ON COLUMN REBOARD.REPHOTO IS '리뷰사진';

CREATE UNIQUE INDEX PK_REBOARD
	ON REBOARD (
		RESEQ ASC
	);

ALTER TABLE REBOARD
	ADD
		CONSTRAINT PK_REBOARD
		PRIMARY KEY (
			RESEQ
		);

/* 미국영화게시판 */
CREATE TABLE ARMOVIE (
	ARSEQ NUMBER NOT NULL, /* 미국영화번호 */
	ARNAME VARCHAR2(100) NOT NULL, /* 미국영화이름 */
	ARCONTENT VARCHAR2(300) NOT NULL, /* 미국영화설명 */
	ARPHOTO VARCHAR2(100) NOT NULL, /* 미국영화사진 */
	ARLIKE NUMBER NOT NULL /* 미국영화추천수 */
);

COMMENT ON TABLE ARMOVIE IS '미국영화게시판';

COMMENT ON COLUMN ARMOVIE.ARSEQ IS '미국영화번호';

COMMENT ON COLUMN ARMOVIE.ARNAME IS '미국영화이름';

COMMENT ON COLUMN ARMOVIE.ARCONTENT IS '미국영화설명';

COMMENT ON COLUMN ARMOVIE.ARPHOTO IS '미국영화사진';

COMMENT ON COLUMN ARMOVIE.ARLIKE IS '미국영화추천수';

CREATE UNIQUE INDEX PK_ARMOVIE
	ON ARMOVIE (
		ARSEQ ASC
	);

ALTER TABLE ARMOVIE
	ADD
		CONSTRAINT PK_ARMOVIE
		PRIMARY KEY (
			ARSEQ
		);

/* 일본영화게시판 */
CREATE TABLE JNMOVIE (
	JNSEQ NUMBER NOT NULL, /* 일본영화번호 */
	JNNAME VARCHAR2(100) NOT NULL, /* 일본영화이름 */
	JNCONTENT VARCHAR2(300) NOT NULL, /* 일본영화설명 */
	JNPHOTO VARCHAR2(100) NOT NULL, /* 일본영화사진 */
	JNLIKE NUMBER NOT NULL /* 일본영화추천수 */
);

COMMENT ON TABLE JNMOVIE IS '일본영화게시판';

COMMENT ON COLUMN JNMOVIE.JNSEQ IS '일본영화번호';

COMMENT ON COLUMN JNMOVIE.JNNAME IS '일본영화이름';

COMMENT ON COLUMN JNMOVIE.JNCONTENT IS '일본영화설명';

COMMENT ON COLUMN JNMOVIE.JNPHOTO IS '일본영화사진';

COMMENT ON COLUMN JNMOVIE.JNLIKE IS '일본영화추천수';

CREATE UNIQUE INDEX PK_JNMOVIE
	ON JNMOVIE (
		JNSEQ ASC
	);

ALTER TABLE JNMOVIE
	ADD
		CONSTRAINT PK_JNMOVIE
		PRIMARY KEY (
			JNSEQ
		);

/* 회원등급 */
CREATE TABLE ROLE (
	RNAME VARCHAR2(20) NOT NULL, /* 롤이름 */
	ID VARCHAR2(100) NOT NULL /* 아이디 */
);

COMMENT ON TABLE ROLE IS '회원등급';

COMMENT ON COLUMN ROLE.RNAME IS '롤이름';

COMMENT ON COLUMN ROLE.ID IS '아이디';

/* 중국영화게시판 */
CREATE TABLE CNMOVIE (
	CNSEQ NUMBER NOT NULL, /* 중국영화번호 */
	CNNAME VARCHAR2(100) NOT NULL, /* 중국영화이름 */
	CNCONTENT VARCHAR2(300) NOT NULL, /* 중국영화설명 */
	CNPHOTO VARCHAR2(100) NOT NULL, /* 중국영화사진 */
	CNLIKE NUMBER NOT NULL /* 중국영화추천수 */
);

COMMENT ON TABLE CNMOVIE IS '중국영화게시판';

COMMENT ON COLUMN CNMOVIE.CNSEQ IS '중국영화번호';

COMMENT ON COLUMN CNMOVIE.CNNAME IS '중국영화이름';

COMMENT ON COLUMN CNMOVIE.CNCONTENT IS '중국영화설명';

COMMENT ON COLUMN CNMOVIE.CNPHOTO IS '중국영화사진';

COMMENT ON COLUMN CNMOVIE.CNLIKE IS '중국영화추천수';

CREATE UNIQUE INDEX PK_CNMOVIE
	ON CNMOVIE (
		CNSEQ ASC
	);

ALTER TABLE CNMOVIE
	ADD
		CONSTRAINT PK_CNMOVIE
		PRIMARY KEY (
			CNSEQ
		);

/* 한국영화게시판 */
CREATE TABLE KRMOVIE (
	KRSEQ NUMBER NOT NULL, /* 한국영화번호 */
	KRNAME VARCHAR2(100) NOT NULL, /* 한국영화이름 */
	KRCONTENT VARCHAR2(300) NOT NULL, /* 한국영화설명 */
	KRPHOTO VARCHAR2(100) NOT NULL, /* 한국영화사진 */
	KRLIKE NUMBER NOT NULL /* 한국영화추천수 */
);

COMMENT ON TABLE KRMOVIE IS '한국영화게시판';

COMMENT ON COLUMN KRMOVIE.KRSEQ IS '한국영화번호';

COMMENT ON COLUMN KRMOVIE.KRNAME IS '한국영화이름';

COMMENT ON COLUMN KRMOVIE.KRCONTENT IS '한국영화설명';

COMMENT ON COLUMN KRMOVIE.KRPHOTO IS '한국영화사진';

COMMENT ON COLUMN KRMOVIE.KRLIKE IS '한국영화추천수';

CREATE UNIQUE INDEX PK_KRMOVIE
	ON KRMOVIE (
		KRSEQ ASC
	);

ALTER TABLE KRMOVIE
	ADD
		CONSTRAINT PK_KRMOVIE
		PRIMARY KEY (
			KRSEQ
		);

/* 유럽영화게시판 */
CREATE TABLE EUMOVIE (
	EUSEQ NUMBER NOT NULL, /* 유럽영화번호 */
	EUNAME VARCHAR2(100) NOT NULL, /* 유럽영화이름 */
	EUCONTENT VARCHAR2(300) NOT NULL, /* 유럽영화설명 */
	EUPHOTO VARCHAR2(100) NOT NULL, /* 유럽영화사진 */
	EULIKE NUMBER NOT NULL /* 유럽영화추천수 */
);

COMMENT ON TABLE EUMOVIE IS '유럽영화게시판';

COMMENT ON COLUMN EUMOVIE.EUSEQ IS '유럽영화번호';

COMMENT ON COLUMN EUMOVIE.EUNAME IS '유럽영화이름';

COMMENT ON COLUMN EUMOVIE.EUCONTENT IS '유럽영화설명';

COMMENT ON COLUMN EUMOVIE.EUPHOTO IS '유럽영화사진';

COMMENT ON COLUMN EUMOVIE.EULIKE IS '유럽영화추천수';

CREATE UNIQUE INDEX PK_EUMOVIE
	ON EUMOVIE (
		EUSEQ ASC
	);

ALTER TABLE EUMOVIE
	ADD
		CONSTRAINT PK_EUMOVIE
		PRIMARY KEY (
			EUSEQ
		);

/* 공지사항 */
CREATE TABLE TABLE (
	NOSEQ NUMBER NOT NULL, /* 공지사항글번호 */
	NONAME VARCHAR2(100) NOT NULL, /* 공지사항이름 */
	NOCONTENT VARCHAR2(1000) NOT NULL /* 공지사항내용 */
);

COMMENT ON TABLE TABLE IS '공지사항';

COMMENT ON COLUMN TABLE.NOSEQ IS '공지사항글번호';

COMMENT ON COLUMN TABLE.NONAME IS '공지사항이름';

COMMENT ON COLUMN TABLE.NOCONTENT IS '공지사항내용';

CREATE UNIQUE INDEX PK_TABLE
	ON TABLE (
		NOSEQ ASC
	);

ALTER TABLE TABLE
	ADD
		CONSTRAINT PK_TABLE
		PRIMARY KEY (
			NOSEQ
		);

/* 덧글 */
CREATE TABLE RECOMENT (
	RSEQ NUMBER NOT NULL, /* 덧글번호 */
	RCONTENT VARCHAR2(300) NOT NULL, /* 덧글내용 */
	CNSEQ NUMBER NOT NULL, /* 중국영화번호 */
	KRSEQ NUMBER NOT NULL, /* 한국영화번호 */
	JNSEQ NUMBER NOT NULL, /* 일본영화번호 */
	ARSEQ NUMBER NOT NULL, /* 미국영화번호 */
	EUSEQ NUMBER NOT NULL, /* 유럽영화번호 */
	ID VARCHAR2(100) NOT NULL /* 아이디 */
);

COMMENT ON TABLE RECOMENT IS '덧글';

COMMENT ON COLUMN RECOMENT.RSEQ IS '덧글번호';

COMMENT ON COLUMN RECOMENT.RCONTENT IS '덧글내용';

COMMENT ON COLUMN RECOMENT.CNSEQ IS '중국영화번호';

COMMENT ON COLUMN RECOMENT.KRSEQ IS '한국영화번호';

COMMENT ON COLUMN RECOMENT.JNSEQ IS '일본영화번호';

COMMENT ON COLUMN RECOMENT.ARSEQ IS '미국영화번호';

COMMENT ON COLUMN RECOMENT.EUSEQ IS '유럽영화번호';

COMMENT ON COLUMN RECOMENT.ID IS '아이디';

CREATE UNIQUE INDEX PK_RECOMENT
	ON RECOMENT (
		RSEQ ASC
	);

ALTER TABLE RECOMENT
	ADD
		CONSTRAINT PK_RECOMENT
		PRIMARY KEY (
			RSEQ
		);

ALTER TABLE JJIM
	ADD
		CONSTRAINT FK_MEMBER_TO_JJIM
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE JJIM
	ADD
		CONSTRAINT FK_REBOARD_TO_JJIM
		FOREIGN KEY (
			RESEQ
		)
		REFERENCES REBOARD (
			RESEQ
		);

ALTER TABLE JJIM
	ADD
		CONSTRAINT FK_ARMOVIE_TO_JJIM
		FOREIGN KEY (
			ARSEQ
		)
		REFERENCES ARMOVIE (
			ARSEQ
		);

ALTER TABLE JJIM
	ADD
		CONSTRAINT FK_CNMOVIE_TO_JJIM
		FOREIGN KEY (
			CNSEQ
		)
		REFERENCES CNMOVIE (
			CNSEQ
		);

ALTER TABLE JJIM
	ADD
		CONSTRAINT FK_JNMOVIE_TO_JJIM
		FOREIGN KEY (
			JNSEQ
		)
		REFERENCES JNMOVIE (
			JNSEQ
		);

ALTER TABLE JJIM
	ADD
		CONSTRAINT FK_EUMOVIE_TO_JJIM
		FOREIGN KEY (
			EUSEQ
		)
		REFERENCES EUMOVIE (
			EUSEQ
		);

ALTER TABLE JJIM
	ADD
		CONSTRAINT FK_KRMOVIE_TO_JJIM
		FOREIGN KEY (
			KRSEQ
		)
		REFERENCES KRMOVIE (
			KRSEQ
		);

ALTER TABLE ROLE
	ADD
		CONSTRAINT FK_MEMBER_TO_ROLE
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE RECOMENT
	ADD
		CONSTRAINT FK_CNMOVIE_TO_RECOMENT
		FOREIGN KEY (
			CNSEQ
		)
		REFERENCES CNMOVIE (
			CNSEQ
		);

ALTER TABLE RECOMENT
	ADD
		CONSTRAINT FK_KRMOVIE_TO_RECOMENT
		FOREIGN KEY (
			KRSEQ
		)
		REFERENCES KRMOVIE (
			KRSEQ
		);

ALTER TABLE RECOMENT
	ADD
		CONSTRAINT FK_JNMOVIE_TO_RECOMENT
		FOREIGN KEY (
			JNSEQ
		)
		REFERENCES JNMOVIE (
			JNSEQ
		);

ALTER TABLE RECOMENT
	ADD
		CONSTRAINT FK_ARMOVIE_TO_RECOMENT
		FOREIGN KEY (
			ARSEQ
		)
		REFERENCES ARMOVIE (
			ARSEQ
		);

ALTER TABLE RECOMENT
	ADD
		CONSTRAINT FK_EUMOVIE_TO_RECOMENT
		FOREIGN KEY (
			EUSEQ
		)
		REFERENCES EUMOVIE (
			EUSEQ
		);

ALTER TABLE RECOMENT
	ADD
		CONSTRAINT FK_MEMBER_TO_RECOMENT
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBER (
			ID
		);
        
        